// Package schema provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package schema

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
	strictecho "github.com/oapi-codegen/runtime/strictmiddleware/echo"
)

// HTTPValidationError defines model for HTTPValidationError.
type HTTPValidationError struct {
	Detail *[]ValidationError `json:"detail,omitempty"`
}

// SampleRequest defines model for SampleRequest.
type SampleRequest struct {
	// Id サンプルAPIのID
	Id *string `json:"id,omitempty"`

	// Params サンプルAPIのパラメータ
	Params *SampleRequest_Params `json:"params"`
}

// SampleRequestParams0 defines model for .
type SampleRequestParams0 = []string

// SampleRequest_Params サンプルAPIのパラメータ
type SampleRequest_Params struct {
	union json.RawMessage
}

// SampleResponse defines model for SampleResponse.
type SampleResponse struct {
	CreatedAt time.Time `json:"created_at"`

	// Name IDに紐づく名称
	Name      *string   `json:"name,omitempty"`
	UpdatedAt time.Time `json:"updated_at"`
}

// ValidationError defines model for ValidationError.
type ValidationError struct {
	Loc  []ValidationError_Loc_Item `json:"loc"`
	Msg  string                     `json:"msg"`
	Type string                     `json:"type"`
}

// ValidationErrorLoc0 defines model for .
type ValidationErrorLoc0 = string

// ValidationErrorLoc1 defines model for .
type ValidationErrorLoc1 = int

// ValidationError_Loc_Item defines model for ValidationError.loc.Item.
type ValidationError_Loc_Item struct {
	union json.RawMessage
}

// ReadRootExampleGetJSONRequestBody defines body for ReadRootExampleGet for application/json ContentType.
type ReadRootExampleGetJSONRequestBody = SampleRequest

// AsSampleRequestParams0 returns the union data inside the SampleRequest_Params as a SampleRequestParams0
func (t SampleRequest_Params) AsSampleRequestParams0() (SampleRequestParams0, error) {
	var body SampleRequestParams0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromSampleRequestParams0 overwrites any union data inside the SampleRequest_Params as the provided SampleRequestParams0
func (t *SampleRequest_Params) FromSampleRequestParams0(v SampleRequestParams0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeSampleRequestParams0 performs a merge with any union data inside the SampleRequest_Params, using the provided SampleRequestParams0
func (t *SampleRequest_Params) MergeSampleRequestParams0(v SampleRequestParams0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t SampleRequest_Params) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *SampleRequest_Params) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsValidationErrorLoc0 returns the union data inside the ValidationError_Loc_Item as a ValidationErrorLoc0
func (t ValidationError_Loc_Item) AsValidationErrorLoc0() (ValidationErrorLoc0, error) {
	var body ValidationErrorLoc0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromValidationErrorLoc0 overwrites any union data inside the ValidationError_Loc_Item as the provided ValidationErrorLoc0
func (t *ValidationError_Loc_Item) FromValidationErrorLoc0(v ValidationErrorLoc0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeValidationErrorLoc0 performs a merge with any union data inside the ValidationError_Loc_Item, using the provided ValidationErrorLoc0
func (t *ValidationError_Loc_Item) MergeValidationErrorLoc0(v ValidationErrorLoc0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsValidationErrorLoc1 returns the union data inside the ValidationError_Loc_Item as a ValidationErrorLoc1
func (t ValidationError_Loc_Item) AsValidationErrorLoc1() (ValidationErrorLoc1, error) {
	var body ValidationErrorLoc1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromValidationErrorLoc1 overwrites any union data inside the ValidationError_Loc_Item as the provided ValidationErrorLoc1
func (t *ValidationError_Loc_Item) FromValidationErrorLoc1(v ValidationErrorLoc1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeValidationErrorLoc1 performs a merge with any union data inside the ValidationError_Loc_Item, using the provided ValidationErrorLoc1
func (t *ValidationError_Loc_Item) MergeValidationErrorLoc1(v ValidationErrorLoc1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t ValidationError_Loc_Item) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *ValidationError_Loc_Item) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Read Root
	// (GET /example)
	ReadRootExampleGet(ctx echo.Context) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// ReadRootExampleGet converts echo context to params.
func (w *ServerInterfaceWrapper) ReadRootExampleGet(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ReadRootExampleGet(ctx)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/example", wrapper.ReadRootExampleGet)

}

type ReadRootExampleGetRequestObject struct {
	Body *ReadRootExampleGetJSONRequestBody
}

type ReadRootExampleGetResponseObject interface {
	VisitReadRootExampleGetResponse(w http.ResponseWriter) error
}

type ReadRootExampleGet200JSONResponse SampleResponse

func (response ReadRootExampleGet200JSONResponse) VisitReadRootExampleGetResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ReadRootExampleGet422JSONResponse HTTPValidationError

func (response ReadRootExampleGet422JSONResponse) VisitReadRootExampleGetResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(422)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Read Root
	// (GET /example)
	ReadRootExampleGet(ctx context.Context, request ReadRootExampleGetRequestObject) (ReadRootExampleGetResponseObject, error)
}

type StrictHandlerFunc = strictecho.StrictEchoHandlerFunc
type StrictMiddlewareFunc = strictecho.StrictEchoMiddlewareFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// ReadRootExampleGet operation middleware
func (sh *strictHandler) ReadRootExampleGet(ctx echo.Context) error {
	var request ReadRootExampleGetRequestObject

	var body ReadRootExampleGetJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ReadRootExampleGet(ctx.Request().Context(), request.(ReadRootExampleGetRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ReadRootExampleGet")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(ReadRootExampleGetResponseObject); ok {
		return validResponse.VisitReadRootExampleGetResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/6xVTW8TMRD9K9HAcWlC4bS3QiuIxEfVFi5Vhdz1JHW1a7u2FxFVOaR74lBRTogjB1Sh",
	"ShUScEPix1hR/waynTS72S3LoTdn8jzz/N7M7DEkIpOCIzca4mPQyQFmxB+f7uxsviYpo8QwwTeUEsqF",
	"pRISlWHoQRQNYak7MYOZD91VOIAY7nQXmbuztN3lfOMIDDMpQgzrIVMEZiTdb6IUGcG4hGgidA0X+4eY",
	"GJdwm2QyxS08ylGbOmNGA+8ByVMDMUAEFHWimHRZIQZ78ssWP2zxyRYXa5t9O7nsr0MEOs8yokZLAP/X",
	"nGCfLvhooxgfOj6SKBKUIXz0cgDxbkmsGrr6+r12crb4aItvtvhii9/25A9EwPM0JfuOkVE53sS8fm/+",
	"jM1AuCx9VdN/iK6l4BrrqicKiUH6hnhHBkJl7gSUGLxnWIal8o8DtLNmmtTkJMMWA/vrdnJx9fPMTr7a",
	"yYfp2enV+feKgdOz0+n701LJFyQwWC6WS/q/rF8FaCPrcQQKj3KmkEK8W9aiUmKvrvdMzgbBWyczFUll",
	"LBfNt/zM6wjjBoeoYLxXsv6ZSHyZ2mRGkOmh7+EZ8jlqTYaNQobAAuo5d3ZctE0t945QaoYsydS6DVwy",
	"xgcidMxNg2Qnl36Wzu3kc8nSpVmDCN6i0uH6/ZXeSs+9TEjkRDKI4YEPuXk3B17xLr7zNrrzEH0LOYM8",
	"3z6FGLaQ0C0hzEbAPUHXECoM2SNBR35wBDfI/WUiZcqCGd1D7WjM93Xb2q2O77gqsVsSPhCazVNf7fVu",
	"vfisl331qhfbeZKg1oM87SxgETxcXb01Ek3fjgYmC0hnjikvDmdYxznm7o7/BgAA//+bGbMKPAcAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
