openapi: 3.1.0
info:
  title: UnevaluatedProperties Sample
  version: 1.0.0
  description: |
    Example using `allOf` inheritance where `unevaluatedProperties: false` ensures strict validation across combined schemas.
paths:
  /products:
    post:
      summary: Create a product
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DetailedProduct'
      responses:
        '201':
          description: Product created

components:
  schemas:
    # ベースとなるスキーマ
    BaseEntity:
      type: object
      properties:
        id:
          type: string
          format: uuid
      required:
        - id

    # ベースを継承しつつ、厳密に検証するスキーマ
    DetailedProduct:
      type: object
      allOf:
        - $ref: '#/components/schemas/BaseEntity'
        - type: object
          properties:
            name:
              type: string
            price:
              type: number
          required:
            - name
      unevaluatedProperties: true